---
busser:
  root_path: /opt/busser
provisioner:
  name: salt_solo
  require_chef_omnibus: false
  require_chef_for_busser: false
  formula: freeipa
  pillars-from-files:
    freeipa.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - freeipa
  state_top:
    base:
      '*':
        - freeipa
  omnibus_cachier: true

platforms:
  - name: vagrant-centos-7
    driver_plugin: vagrant
    driver_config:
      vagrantfile_erb: "kitchenvagrant/Vagrantfile.erb"
      cachier:
        scope: "box"
      customize:
        memory: 1024
      box: "rocketman110us/centos71-saltminion"

suites:
  - name: default
